### ISSUE TITLE
pip failed to build package: aiohttp

### ISSUE THREAD

**Issue by josephlopez86** [datawhores/OF-Scraper#225]
Installing via pipx on a Mac using Python 3.11.4 which has worked in the past (says its of-scraper 2.7.13 if that helps), but upgraded macOS to Sonoma (not of-scraper as it happens) and some other stuff messed up so trying to re-install on a fresh Ventura machine.

Fatal error from pip prevented installation. Full pip output in file:
    /Users/user/.local/pipx/logs/cmd_2023-10-07_13.18.10_pip_errors.log

pip failed to build package:
    aiohttp

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    aiohttp/_websocket.c:3042:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3097:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3238:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3293:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3744:47: error: no member named 'ob_digit' in 'struct _longobject'
    error: command '/usr/bin/clang' failed with exit code 1

Error installing ofscraper.

last few lines when cat of the log file is as follows.... let me know if need more

      6 warnings and 5 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

**Comment by CannotTouch** [comment]
if i don't remember wrong you should use python 3.10 not the 3.11 or more... check on the installation page info

**Comment by josephlopez86** [comment]
says Python 3.10.12+, but not 3.13 - which would imply 3.11.x is ok.... that said I was open to rolling down to 3.10.12 but wasn't available for download for Mac on the Python page. Also tried 3.11.0 and 3.12 checking the Python version with python3 -V everytime to check the version changes but still no dice

**Comment by josephlopez86** [comment]
havent used in anger yet, but believe I've sorted it - followed the instructions for installing pyenv then installing 3.10.12 within that and then using that version to install the scraper via 

pipx install ofscraper --python /Users/user/.pyenv/versions/3.10.12/bin/python3.10

would have seemingly been much simplier if Python still offered 3.10.12 for download for macOS
